apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default  # 👈 Add this line
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
